### ISSUE TITLE
Using account_create RPC call is very slow, about a few minutes, but using the command line is very fast，why?

### ISSUE THREAD

**Issue by luis360** [nanocurrency/nano-node#2867] opened 2020-08-03 06:47 UTC
curl -XPOST 127.0.0.1:7076 -d '{"action":"account_create","wallet":"xxx"}'
very slow

but cmd is very fast.
![image](https://user-images.githubusercontent.com/38502473/89153766-23c3c800-d598-11ea-8c27-f3f7a6097ed3.png)

**Comment by guilhermelawless** [comment] 2020-08-03 07:13
Hi there, please provide the following information:
- Node version
- Last log file after running the RPC command that takes a few minutes

Do other RPC calls take long or only this one?

**Comment by luis360** [comment] 2020-08-03 07:24
version: 21.1
2020-Aug-03 06:28:11.946761]: 0x7f7c10534b30 {"action":"account_create","wallet":"70XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}
[2020-Aug-03 06:28:39.181073]: 32833 blocks (+ 0 state blocks) (+ 0 forced) in processing queue
[2020-Aug-03 06:28:39.274181]: 348604 accounts in pull queue
[2020-Aug-03 06:29:11.331460]: 348076 accounts in pull queue
[2020-Aug-03 06:29:13.068979]: 33136 blocks (+ 0 state blocks) (+ 0 forced) in processing queue
[2020-Aug-03 06:29:45.330134]: 347412 accounts in pull queue
[2020-Aug-03 06:29:46.820233]: 33280 blocks (+ 0 state blocks) (+ 0 forced) in processing queue
[2020-Aug-03 06:30:19.196281]: 346965 accounts in pull queue
[2020-Aug-03 06:30:22.373860]: 33316 blocks (+ 0 state blocks) (+ 0 forced) in processing queue
[2020-Aug-03 06:30:54.368470]: 345813 accounts in pull queue
[2020-Aug-03 06:31:16.822608]: 32955 blocks (+ 0 state blocks) (+ 0 forced) in processing queue
[2020-Aug-03 06:31:17.378337]: 345801 accounts in pull queue
[2020-Aug-03 06:31:31.013510]: UPnP No IGD devices found
[2020-Aug-03 06:31:49.386973]: 345540 accounts in pull queue
[2020-Aug-03 06:32:21.411369]: 345539 accounts in pull queue
[2020-Aug-03 06:32:25.316034]: 34122 blocks (+ 0 state blocks) (+ 0 forced) in processing queue
[2020-Aug-03 06:32:57.347472]: 344933 accounts in pull queue
[2020-Aug-03 06:33:29.442910]: 344927 accounts in pull queue
[2020-Aug-03 06:33:41.164519]: 33098 blocks (+ 0 state blocks) (+ 0 forced) in processing queue
[2020-Aug-03 06:33:44.449077]: 344409 accounts in pull queue
[2020-Aug-03 06:34:13.312650]: 344249 accounts in pull queue
[2020-Aug-03 06:34:25.533129]: 33142 blocks (+ 0 state blocks) (+ 0 forced) in processing queue
[2020-Aug-03 06:34:28.314403]: 343654 accounts in pull queue
[2020-Aug-03 06:34:58.494930]: 343293 accounts in pull queue
[2020-Aug-03 06:35:05.141619]: 32843 blocks (+ 0 state blocks) (+ 0 forced) in processing queue
[2020-Aug-03 06:35:13.504085]: 342682 accounts in pull queue
[2020-Aug-03 06:35:37.449336]: 342664 accounts in pull queue
[2020-Aug-03 06:35:55.625987]: 33150 blocks (+ 0 state blocks) (+ 0 forced) in processing queue
[2020-Aug-03 06:35:56.523780]: 342661 accounts in pull queue
[2020-Aug-03 06:36:28.391070]: 342309 accounts in pull queue
[2020-Aug-03 06:36:39.020525]: UPnP No IGD devices found
[2020-Aug-03 06:36:41.727679]: 33111 blocks (+ 0 state blocks) (+ 0 forced) in processing queue
[2020-Aug-03 06:36:41.727730]: Beginning pending block search
[2020-Aug-03 06:36:43.394526]: 342061 accounts in pull queue
[2020-Aug-03 06:37:14.567577]: 341623 accounts in pull queue
[2020-Aug-03 06:37:21.932368]: 33113 blocks (+ 0 state blocks) (+ 0 forced) in processing queue
[2020-Aug-03 06:37:30.638461]: 340649 accounts in pull queue
[2020-Aug-03 06:37:53.927070]: 32830 blocks (+ 0 state blocks) (+ 0 forced) in processing queue
[2020-Aug-03 06:37:54.435147]: 340632 accounts in pull queue
[2020-Aug-03 06:38:26.524621]: 33171 blocks (+ 0 state blocks) (+ 0 forced) in processing queue
[2020-Aug-03 06:38:26.611857]: 339658 accounts in pull queue
[2020-Aug-03 06:38:58.615988]: 339100 accounts in pull queue
[2020-Aug-03 06:38:59.171935]: 33072 blocks (+ 0 state blocks) (+ 0 forced) in processing queue
[2020-Aug-03 06:39:29.437711]: 32913 blocks (+ 0 state blocks) (+ 0 forced) in processing queue
[2020-Aug-03 06:39:30.656049]: 338425 accounts in pull queue
[2020-Aug-03 06:39:48.655247]: 337857 accounts in pull queue
[2020-Aug-03 06:39:57.894679]: 33202 blocks (+ 0 state blocks) (+ 0 forced) in processing queue
[2020-Aug-03 06:40:03.667431]: 337113 accounts in pull queue
[2020-Aug-03 06:40:25.917012]: 32852 blocks (+ 0 state blocks) (+ 0 forced) in processing queue
[2020-Aug-03 06:40:26.698871]: 337034 accounts in pull queue
[2020-Aug-03 06:40:54.420286]: 33160 blocks (+ 0 state blocks) (+ 0 forced) in processing queue
[2020-Aug-03 06:40:55.694982]: 336066 accounts in pull queue
[2020-Aug-03 06:41:22.639135]: 32857 blocks (+ 0 state blocks) (+ 0 forced) in processing queue
[2020-Aug-03 06:41:23.563547]: 335585 accounts in pull queue
[2020-Aug-03 06:41:47.028212]: UPnP No IGD devices found
[2020-Aug-03 06:41:49.136937]: 33209 blocks (+ 0 state blocks) (+ 0 forced) in processing queue
[2020-Aug-03 06:41:49.735146]: 335073 accounts in pull queue

wallet_create is also very slow.

**Comment by luis360** [comment] 2020-08-03 07:49
![image](https://user-images.githubusercontent.com/38502473/89157298-e151b980-d59e-11ea-8c25-605011bae2a1.png)

RPC request 0x7f7c240ae460 completed in: 372795242 microseconds

**Comment by luis360** [comment] 2020-08-03 08:04
wallet_create:
![image](https://user-images.githubusercontent.com/38502473/89160058-0a744900-d5a3-11ea-838c-c182dd347a53.png)

**Comment by luis360** [comment] 2020-08-03 08:06
> Hi there, please provide the following information:
> 
> * Node version
> * Last log file after running the RPC command that takes a few minutes
> 
> Do other RPC calls take long or only this one?


Please see my comment.
thank you.

**Comment by guilhermelawless** [comment] 2020-08-03 08:18
Thank you for the logs, it all points to the node being very busy doing some task. Could you provide the following as well?
- Hardware details
- Size of your `data.ldb` and `wallet.ldb` files.
- Response of RPC `{"action": "block_count"}`
- Response of RPC `{"action": "stats", "type": "objects"}`  when wallet_create/account_create is taking very long
- Command you're using to start the node.

Please provide everything in a single comment if possible, use attachments / gists if needed.

**Comment by luis360** [comment] 2020-08-03 08:45
> Thank you for the logs, it all points to the node being very busy doing some task. Could you provide the following as well?
> 
> * Hardware details
> * Size of your `data.ldb` and `wallet.ldb` files.
> * Response of RPC `{"action": "block_count"}`
> * Response of RPC `{"action": "stats", "type": "objects"}`  when wallet_create/account_create is taking very long
> * Command you're using to start the node.
> 
> Please provide everything in a single comment if possible, use attachments / gists if needed.

node runs in docker

host:
cpu:8 core 
hd: 2.0T
mem: 64G

data.ldb: 47G
wallet.ldb: 60k

 curl -XPOST 127.0.0.1:7076 -d '{"action":"block_count"}'
{
    "count": "26017607",
    "unchecked": "26070157",
    "cemented": "16484026"
}
curl -XPOST 127.0.0.1:7076 -d '{"action": "stats", "type": "objects"}'
{
    "node": {
        "alarm": {
            "operations": {
                "count": "1728",
                "size": "69120"
            }
        },
        "work": {
            "pending": {
                "count": "0",
                "size": "0"
            },
            "work_observers": {
                "observers": {
                    "count": "0",
                    "size": "0"
                }
            }
        },
        "gap_cache": {
            "blocks": {
                "count": "256",
                "size": "18432"
            }
        },
        "ledger": {
            "bootstrap_weights": {
                "count": "0",
                "size": "0"
            },
            "rep_weights": {
                "rep_amounts": {
                    "count": "21035",
                    "size": "1009680"
                }
            }
        },
        "active": {
            "roots": {
                "count": "0",
                "size": "0"
            },
            "blocks": {
                "count": "0",
                "size": "0"
            },
            "election_winner_details": {
                "count": "0",
                "size": "0"
            },
            "recently_confirmed": {
                "count": "0",
                "size": "0"
            },
            "recently_cemented": {
                "count": "0",
                "size": "0"
            },
            "priority_wallet_cementable_frontiers_count": {
                "count": "0",
                "size": "0"
            },
            "priority_cementable_frontiers_count": {
                "count": "0",
                "size": "0"
            },
            "inactive_votes_cache_count": {
                "count": "5082",
                "size": "365904"
            },
            "generator": {
                "state_blocks": {
                    "count": "0",
                    "size": "0"
                }
            }
        },
        "bootstrap_initiator": {
            "observers": {
                "count": "0",
                "size": "0"
            },
            "pulls_cache": {
                "count": "0",
                "size": "0"
            }
        },
        "bootstrap": {
            "connections": {
                "count": "0",
                "size": "0"
            }
        },
        "network": {
            "tcp_channels": {
                "channels": {
                    "count": "184",
                    "size": "8832"
                },
                "attempts": {
                    "count": "130",
                    "size": "9360"
                },
                "node_id_handshake_sockets": {
                    "count": "2",
                    "size": "32"
                }
            },
            "udp_channels": {
                "channels": {
                    "count": "0",
                    "size": "0"
                },
                "attempts": {
                    "count": "0",
                    "size": "0"
                }
            },
            "syn_cookies": {
                "syn_cookies": {
                    "count": "0",
                    "size": "0"
                },
                "syn_cookies_per_ip": {
                    "count": "188",
                    "size": "7520"
                }
            },
            "excluded_peers": {
                "peers": {
                    "count": "0",
                    "size": "0"
                }
            }
        },
        "telemetry": {
            "recent_or_initial_request_telemetry_data": {
                "count": "143",
                "size": "37752"
            },
            "callbacks": {
                "count": "0",
                "size": "0"
            }
        },
        "observers": {
            "blocks": {
                "observers": {
                    "count": "3",
                    "size": "96"
                }
            },
            "wallet": {
                "observers": {
                    "count": "0",
                    "size": "0"
                }
            },
            "vote": {
                "observers": {
                    "count": "1",
                    "size": "32"
                }
            },
            "active_stopped": {
                "observers": {
                    "count": "0",
                    "size": "0"
                }
            },
            "account_balance": {
                "observers": {
                    "count": "0",
                    "size": "0"
                }
            },
            "endpoint": {
                "observers": {
                    "count": "2",
                    "size": "64"
                }
            },
            "disconnect": {
                "observers": {
                    "count": "0",
                    "size": "0"
                }
            },
            "work_cancel": {
                "observers": {
                    "count": "1",
                    "size": "32"
                }
            }
        },
        "wallets": {
            "items": {
                "count": "6",
                "size": "288"
            },
            "actions": {
                "count": "0",
                "size": "0"
            },
            "work_watcher": {
                "count": "0",
                "size": "0"
            }
        },
        "vote_processor": {
            "votes": {
                "count": "0",
                "size": "0"
            },
            "representatives_1": {
                "count": "118",
                "size": "3776"
            },
            "representatives_2": {
                "count": "32",
                "size": "1024"
            },
            "representatives_3": {
                "count": "10",
                "size": "320"
            }
        },
        "rep_crawler": {
            "active": {
                "count": "0",
                "size": "0"
            }
        },
        "block_processor": {
            "state_block_signature_verification": {
                "state_blocks": {
                    "count": "0",
                    "size": "0"
                }
            },
            "blocks": {
                "count": "33012",
                "size": "2112768"
            },
            "forced": {
                "count": "0",
                "size": "0"
            }
        },
        "block_arrival": {
            "arrival": {
                "count": "1414",
                "size": "56560"
            }
        },
        "online_reps": {
            "reps": {
                "count": "94",
                "size": "3008"
            }
        },
        "votes_cache": {
            "cache": {
                "count": "0",
                "size": "0"
            }
        },
        "block_uniquer": {
            "blocks": {
                "count": "0",
                "size": "0"
            }
        },
        "vote_uniquer": {
            "votes": {
                "count": "0",
                "size": "0"
            }
        },
        "confirmation_height_processor": {
            "cemented_observers": {
                "count": "1",
                "size": "32"
            },
            "block_already_cemented_observers": {
                "count": "1",
                "size": "32"
            },
            "awaiting_processing": {
                "count": "0",
                "size": "0"
            },
            "bounded_processor": {
                "pending_writes": {
                    "count": "0",
                    "size": "0"
                },
                "accounts_confirmed_info": {
                    "count": "0",
                    "size": "0"
                }
            },
            "unbounded_processor": {
                "confirmed_iterated_pairs": {
                    "count": "0",
                    "size": "0"
                },
                "pending_writes": {
                    "count": "0",
                    "size": "0"
                },
                "implicit_receive_cemented_mapping": {
                    "count": "0",
                    "size": "0"
                },
                "block_cache": {
                    "count": "0",
                    "size": "0"
                }
            }
        },
        "worker": {
            "queue": {
                "count": "3945",
                "size": "126240"
            }
        },
        "distributed_work": {
            "items": {
                "count": "1",
                "size": "56"
            }
        },
        "request_aggregator": {
            "pools": {
                "count": "0",
                "size": "0"
            }
        }
    }
}


cmd: /root/nano/bin/nano_node  --config rpc.enable=true --config rpc.enable_control=true --daemon

**Comment by guilhermelawless** [comment] 2020-08-03 08:54
Thank you, the problem is the amount of worker tasks queued that seem to be taking a long time. Given the size of the database, it seems you might have run into an LMDB bug that inflates and slows down the database.

It should be solved by either:
- Running https://docs.nano.org/commands/command-line-interface/#-vacuum
- Removing `data.ldb` to start from scratch. You can also download a database following details in https://docs.nano.org/running-a-node/ledger-management/#downloaded-ledger-files

Let me know how it goes and sorry you ran into this!

**Comment by luis360** [comment] 2020-08-03 09:37
> Thank you, the problem is the amount of worker tasks queued that seem to be taking a long time. Given the size of the database, it seems you might have run into an LMDB bug that inflates and slows down the database.
> 
> It should be solved by either:
> 
> * Running https://docs.nano.org/commands/command-line-interface/#-vacuum
> * Removing `data.ldb` to start from scratch. You can also download a database following details in https://docs.nano.org/running-a-node/ledger-management/#downloaded-ledger-files
> 
> Let me know how it goes and sorry you ran into this!

I used the first method and restarted, both accout_create and wallet_create are very fast.
thank you.
but my upgrade from 21.0 to 21.1 is very slow, it has been several hours, and the upgrade has not been completed yet.
only print `Upgrade in progress`. why? how long will it take to complete.

**Comment by guilhermelawless** [comment] 2020-08-03 10:09
I don't understand, you said you were already running V21.1. There is no upgrade from V21.0 to V21.1, if the RPC is accessible then the upgrade is complete and you are good to go.

In case you're not aware, your node is not yet caught up with the network. This will only happen once block_count (cemented count) reaches ~52 million.

**Comment by guilhermelawless** [comment] 2020-08-03 10:11
Closing as it's moving to another topic, feel free to reach out on [Discord](https://chat.nano.org) for support as well, or create a new ticket with enough information.

**Closed as completed by guilhermelawless** 2020-08-03 10:11 UTC

**Comment by luis360** [comment] 2020-08-03 15:24
> I don't understand, you said you were already running V21.1. There is no upgrade from V21.0 to V21.1, if the RPC is accessible then the upgrade is complete and you are good to go.
> 
> In case you're not aware, your node is not yet caught up with the network. This will only happen once block_count (cemented count) reaches ~52 million.

sorry, stage had slow question, online I'm upgrading.
