### ISSUE TITLE
Proposal: Dynamic PoW difficulty based on network TX per second

### ISSUE THREAD

**Issue by SergiySW** [nanocurrency/nano-node#196] opened 2017-10-02 09:33 UTC
Current user-generated PoW is too high for large services & mobile users. Also it cannot fully prevent large-scale TX attack.
With dynamic PoW difficulty representative nodes can increase required block threshold under spam attack attempt & keep it easy in usual situations.

**Comment by HostFat** [comment] 2017-10-29 21:11
I'm not sure that it is easy to understand when there is a spam attack and when there are just many new users.
Something dynamic can be added, but I think that the PoW difficulty should be changed with stake voting.

**Comment by thehen101** [comment] 2017-12-14 13:39
Suggestion: the servers which the lite phone wallets connect to can compute the PoW for them but for a small fee. This means instant transactions for anyone on a phone, BUT it may drive a few mobile users away.

Perhaps the network could also vote to reject obvious malicious transactions that are being spammed around the network (to stop a bot playing ping pong with 2 addresses and some XRB). Perhaps malicious IPs could also be blocked by the network temporarily.

**Comment by DavidCMoncrief** [comment] 2017-12-15 08:05
@SamHolmes . I have a philosophical and practical issue with the POW being linked to your stake.  Many users of Rai are likely to be from developing countries and may not have much XRB to begin with, and would likely use a mobile phone for transactions. I've thought about this a bit and maybe its possible in the future for the POW to be done by the point of sale machine..

There needs to be a way to identify network cloggers and put them on a shot clock or increase POW. IOTA is dealing with this now and CFB stated something to the degree of "we know how to turn it off, we're just collecting data so we  better understand the attack".

@thehen101 I do not think paying a fee for fast laning the transaction or even a fee to be able to use the mobile wallet should be implemented.  That is what makes rai fundamentally different (and IMHO better) than all other crytocurrencies. While I guess there is nothing stopping a third party from providing this service, I'm not sure if it would be responded to well.

**Comment by harsh-deshpande** [comment] 2018-01-14 08:20
Instead of dynamically changing the PoW difficulty, we keep the difficulty fixed. But instead vary the prefix dynamically every ten minutes or so. For instance, instead of expecting, say, 10 zeros as the prefix in the computed hash (which is what a threshold essentially does), we instead expect a random string of bits that changes every 10 minutes or so as the prefix. If we don't vary the length of the prefix, the difficulty stays the same. At the same time, no one can pre-compute the nonce since they don't know what the prefix is gonna be.

**Comment by androm3da** [comment] 2018-01-23 04:19
The dynamic PoW sounds like a reasonable idea but it has to be something that all nodes can perceive in a stable way so that transactions can operate seamlessly.  How can all nodes calculate the difficulty if "tx rate" is an input?  They cannot.  Some nodes will see different rates based on global network topology and activity levels.  Router congestion will cause datagrams to be lost, so consensus on the tx rate could be formed.

Accepting a transaction fee of any size would effectively renegotiate the value proposition of the coin.  This would be similar to Bitcoin deciding that they no longer want to have an inflation limit or they want to increase the inflation rate.

**Comment by scott79** [comment] 2018-07-28 02:56
If voting occurs on all blocks, can rate limiting the # of txs voted on for an account based on value held in account be a solution. Measurement can be done by implementing a block window size for rate detection. Voting rate should be dynamic and can/should be proportional to account's total available balance, total available supply, block rate activity, and other criterion.

Txs in breach are stored in a LRU queue which can result in lost of vote or simply delayed voting.

**Comment by alandefreitas** [comment] 2018-08-07 17:11
Now that representatives will vote with musig (and only then the node will relay the final transaction with the vote aggregation to the network) couldn't we just get rid of PoW?

Not trivially, of course:

A preliminary idea is that representatives would attribute a timestamp `t` for the hash and sign both. This would become the official and final timestamp for the transaction. After that, spam could be filtered in one of two ways:
* Static: If the user initiates a new transaction before `t+s`, the transaction is not signed by the representative. `s` can take as long as PoW currently takes.
* Dynamic: An user can initiate a transaction at any time. Representatives keep a list of unprocessed transactions in a Fibonacci heap (Boost implements it as a container) where the criterion for priority is the distance from the last timestamp. Spam would just go to the end of the queue.

The dynamic approach would not only allow transactions to go as fast as the representatives can process but it would also give a clear advantage to honest users, who would have their transactions processed almost instantly.

The obvious attacks are:
* A spammer could use multiple accounts: note that the user can use multiple accounts but he can preprocess the PoW because what would count is the real timestamp. The problem of multiple accounts to get around the timestamps can be solved by using the history of the output and the IP of the node initiating the transaction in the priority criteria of the Fibonacci heap. Over time, we could in principle think of other useful criteria. It seems to me that the best future criteria would be a Bayesian estimate of the probability that something is spam. All kinds of data could be in the estimate and the cost of evaluating these is constant.
* A simple DoS attack with many invalid transactions to take down the representative or make the heap bigger than the representative's capacity: this problem is no different than what it would be if the unprocessed transactions are kept in a vector or any other data structure. In any case, we need logical cut-offs that could be evaluated in constant time such as (i) accounts should only have one transaction on the list, and (ii) timestamp deltas that are very different from the network capacity could be discarded immediately as outliers.

Regarding the capacity of representatives, they can also increase their capacity by validating transactions in parallel according to the transaction hash. Representative `k` can be online on `IPk1`, `IPk2`, ... `IPkn`. If a transaction is preimage for the hash `h`, such that `h%n==i`, this transaction will be validated by `IPk(i+1)`. The user can send the transaction directly to `IPk(i+1)`. If the transaction goes to another IP such that `h%n!=i`, the representative will send it to the proper `IPk(i+1)` and it's not included in the heap. So any node can validate `x` times more transactions by setting up more nodes with the same private key.

This would move NANO closer to what the internet (and e-mail) looks like. Invalid transactions (like spam) would be invalidated or given preference according to their properties rather than imposing a cost on all honest users.

**Comment by AyiSoli** [comment] 2018-08-12 05:44
With increasing the PoW, the effect of it must be assessed from a allied service operators perspective - how will wallet providers, exchanges, deal with it? What could be the impact? Its safe to say majority of the users of the network will rely upon subsidised PoW servers. 
The value of the transaction should also be a factor, under a spam or high tps scenario, pow for a low value transaction should me higher than the pow for a high value transaction.

**Comment by P0ar** [comment] 2018-08-12 09:47
I think it's worth leaving here what colin said in the closed issue above: 

"We have plans for a queueing mechanism weighted on (least recently used account) * (amount) * (PoW difficulty). Nodes will be able to dynamically increase the PoW difficulty they generate to get prioritization."

**Comment by Laurentiu-Andronache** [comment] 2018-08-13 13:14
@samholmes has given the solution

> the smaller the account balance the more hash power is required in the dynamic PoW difficulty. This means that 0 XRB transactions would require the utmost amount of PoW, while transactions with larger units of XRB would require less PoW. With this in place, to conduct an effective Precompiled PoW attack you would need a greater amount of accounts containing significant amount of XRB balances. This would cost the attacker computing power in addition to cost of stake in the network.

It's perfect really!

**Comment by samholmes** [comment] 2018-08-14 21:09
@Laurentiu-Andronache The only downside as mentioned by @DavidCMoncrief is that poorer economies (countries) would be at a disadvantage when using the currency. Not only would those people have less money and therefore smaller transactions, they would also have less resources when it comes to computing power/hash power. So the problem has to do with the non-uniformity of capital across the globe.

I think this suggests that there should be more localized sub-networks within the whole network. Transactions within a poorer network don't concern themselves with transactions within a richer network usually. If there was a way to identify sub-networks and determine the required hash rate for transactions, then we would have a more asynchronous network overall. The only challenge is when these sub-networks need to interact: in that case requiring more PoW for transactions from the poorer sub-net to the richer sub-net is an understandable expense. There would still be the issue that these poorer sub-networks would be less secure when it comes to spam, but would there be much economic incentive to spam such a poorer sub-network? Maybe not. This is just another idea I'll though out there.

**Comment by kvrban** [comment] 2018-08-14 22:10
On Reddit was a discussion about this topic to dynamically adjust the
PoW difficulty.
Maybe some stimuli to find:
https://www.reddit.com/r/nanocurrency/comments/8y0ljp/what_is_the_incentive_to_spam_the_nano_network/e279oy7

My comment was: that any type of account based PoW adjustment could only
work, if opening new accounts is much more PoW expensive
then normal transfer transactions. Otherwise a attacker just spam with many
new opened accounts.
High PoW cost to open a new accounts hit spammer much harder, not normal
Nano user, which use their accounts long-term.

**Comment by guilhermelawless** [comment] 2018-08-14 22:17
@kvrban The problem is that it also hits use-cases such as payment processors, who create an account for each transaction. At least, Brainblocks does.

**Comment by Inkeliz** [comment] 2018-08-23 21:39
I think we need to fight against pre-computed PoW, not increasing the PoW at first time. Even if the dinamyc PoW the attacker can compute a PoW that meets the new requirements. For instance, if today is hash < 100, the attacker can already pre-compute a hash < 80, if the difficult increases to hash < 90, the attacker already have it.

In my point of view that prevents a pre-computed PoW is a timestamp-like. The signature is chaotic and not predicable, but verifiable. 

My idea is something like, but not exactly:
1.	All > 0.1% voters chooses a difficult and combine with a rounded unix-timestamp and the sequence (if change votes are needed), then signs: Ed25516(difficult || unix-time || sequence).
2.	When the nodes agree with the values, the node need to create a pow using all signatures as part of the derivation. So, something like Blake2(size = 8, message = Nonce || *AllVotersSignatures* || previous)
In this case, the only way to pre-compute the PoW is predicting the signature of all nodes, which is not possible. The main problem is getting a consensus, because someone desync can consider that have all signature, but not. However, it’s the idea. 

If I understand the VoteStapling (https://github.com/nanocurrency/raiblocks/pull/1006), it can be used in the same way. If this vote has a lifetime to be approved, so the PoW includes the VoteStapling in the derivation.

**Comment by rkeene** [comment] 2018-10-12 18:19
As a follow-on to #1298 we will be investigating changing the floor (work minimum) dynamically based on network conditions -- transactions below the current floor won't get added to the queue created as part of #1298

**Comment by zhyatt** [comment] 2019-02-12 18:58
Related to https://github.com/nanocurrency/nano-node/issues/1336

**Comment by gabparrot** [comment] 2019-06-26 18:39
Why not have an algorithm with multiple factors instead of trying to find a 1 level solution? Now, maybe this isn't feasible, as I'm not as knowledgeable as you all but instead of just comparing PoW done for a block vs present PoW floor, couldn't it be individually, score based, while still being dynamic?

Example:
- If network conditions are good, PoW stays at minimum (and no receive block PoW?)
- As network conditions worsen, accounts need to output a PoW higher than floor divided by account score
- Account score factors in things like flagged for spam, account balance, tx size, age (current block - open block).
- Higher ranking accounts have very little PoW to do. Fresh accounts making tiny transactions will have to adapt to the dynamic PoW, flushing out spam accounts without punishing too many accounts.
- Could also be done in levels. Like network 2/5 clogged means level 1 and 2 accounts have to output a higher PoW but the higher scoring accounts would be exempted. 
- Poorer accounts would still have a good score from the other factors

Most of this calculation could be done locally without the need for more bandwidth. At least I think.

This would open the door for an even smaller standard PoW.

**Comment by zhyatt** [comment] 2019-06-27 18:14
Just a note to clarify that Dynamic PoW is being implemented in V19 through various PRs, some of which can be seen in https://github.com/nanocurrency/nano-node/issues/1336. This issue was kept open and moved to the Research for Future Release milestone because there were discussions and suggestions for other types of PoW changes we wanted to keep alive and in consideration going forward.

**Comment by paulharwood** [comment] 2021-02-05 01:22
Can the node/network also reject transactions with a threshold of say less than 90% of the current difficulty? Not reaching a difficulty threshold may render pre-computed attacks useless and protect the tx from ever being rebroadcast, effectively localising the problem.

Does the difficulty need to be uniform over the network?

Excuse my ignorance if i've not understood the protocol well enough for these questions to be valid.

**Comment by zhyatt** [comment] 2021-02-05 15:08
> Can the node/network also reject transactions with a threshold of say less than 90% of the current difficulty? Not reaching a difficulty threshold may render pre-computed attacks useless and protect the tx from ever being rebroadcast, effectively localising the problem.
> 
> Does the difficulty need to be uniform over the network?
> 
> Excuse my ignorance if i've not understood the protocol well enough for these questions to be valid.

One of the issues with this approach is that due to the asynchronous nature of the network, nodes could be seeing a different set/order of transactions in any given time period. Since work difficulty can be changed on a block before confirmation, that also means potentially different levels seen for an individual block at different times. This isn't a major issue when those transactions are kept around and eventually resolved, but if you start dropping them at a threshold, then different nodes across the network may not have the same set of blocks they are trying to reach confirmation on. This misalignment slows down the ability to clear elections, requires bootstrapping dropped blocks that were prioritized on some nodes but dropped on others, and other effects that reduce efficiency.

There have been discussions of trying to get the Principal Representatives to agree on certain common levels, this type of difficulty threshold could be a candidate for that, but in order to come to agreement you need more communication/negotiation/consensus which is costly. This could still be worth it given the potential throttle this could provide under load but before the network is overwhelmed, and then when not under load the extra bandwidth and resource between PRs isn't as concerning.

**Comment by RobbertJanSW** [comment] 2021-03-12 10:24
[edit2]
I just noticed we already have something like this implemented by now.. :-)
[/edit2]

How about adjusting the difficulty based on the blocks reaching quorum at any given moment? Without extra negotiation, but simply based upon the current network quorum and block difficulty already in there.

In the end, it's all about the PR nodes being able to vote. Spam is only a problem when it is saturating (too much) PR nodes, impacting the ability to reach quorum on the network.

A PR node can independently determine whether it is healthy or lagging behind. Once it starts lagging behind (unchecked blocks), it can adjust it's own difficulty requirement for new blocks to be processed / voted upon. The more it lags behind, the higher it will adjust it's difficulty threshold. When every PR does this for itself, each PR would start throttling the processing of incoming blocks when it becomes overwhelmed. In such a way that it only processes the blocks coming in with the highest difficulty.

Now consider multiple PRs start throttling this way as a result of a spam attack. Blocks reaching quorum would have a difficulty that's consistent with a load that can be handled by PRs representing >50% of the voting weight under the current TX load.

So any node on the network can create new TXs based upon the difficulty in the last 'n' blocks reaching quorum.

Naturally, difficulty has to be able to ease back down. So nodes would have to create new blocks based upon lowest quorum-reached block, resulting in all new blocks to have a difficulty ranging from a littlebit lower, to some range above, that "quorum difficulty".

Example, when a node creates a new TX/block:
difficultyNetworkTarget = lowest difficulty of all blocks reaching quorum in the last second
difficultyNewBlock = difficultyNetworkTarget + (rand ( -1, 1000) )

Values are just exemplary, of course. But the idea is nodes start creating blocks in a difficulty range ranging from 0.1% (a little) below what the network was able to handle in the last second, and  99.9% (a little) above it. With a set minimum, of course. So when the network is not overloaded, all block would be created with a random difficulty at or just above the very lowest difficulty. When it starts being overloaded, blocks would be generated within a difficulty range that is climing.

Once a spam attack starts, PRs would keep themselves healhy. Delaying only the TXs/blocks having the lowest difficulty until the attack is over. Nodes will in turn start creating blocks with a difficulty the network can handle. Once spam stops, PRs over time process the blocks with lower difficulty, lowering the quorum-reaching difficulty. In turn, the difficuly range within newly created blocks will start to ease back down.

On top of all this, the difficulty should always have a block-based (account based?) weight factor of some kind. Requiring very small TXs sending just-received coins to have a higher difficulty. So when speaking of quorum-reaching difficulty, I mean "effective difficulty". Being the actual difficulty in a block minus a penalty. Penalty being 0 or higher, based upon factors like tiagocanto01 proposed in aug 2018.

Consider in all this that when I say 'difficulty', this can be implemented as any form of difficulty (POW/POS). Lets not assume we need POW here.

[edit]
In fact, since all newly created blocks in this concept would already have slightly different difficulty falling inside the 'load range' of the last second, PRs dont even have to adjust their difficulty actively; they only have to process blocks prioritized by block difficulty.

All this should be combined with the requirement to sign a block including some kind of proof it has been created in-time (recently). For this, please see inkeliz's comment earlier. This would prevent precompiled spam attacks with build-in higher block difficulty. Maybe it is worth to consider dropping blocks created with a way higher difficulty than the current quorum-reaching difficulty. That would throttle a precompiled spa, attack in itself, since the pace of difficulty adjustments is difficult to predict.
[/edit]

**Comment by RobbertJanSW** [comment] 2021-03-12 11:30
Thinking about this some more, it might be even better to have PRs process blocks prioritized by the difference between the effective block difficulty and the last-second quorum reaching difficulty. This way every node and PR has its own loosely difficulty-based processing and block generation. Effectively this would prioritize blocks having a difficulty closest to the current load the network is processing. But in itself is chaotic enough to penalize any precompiled work, since blocks having smaller OR greater difficulty than the current quorum diff would be delayed in favor of those who are generated based upon the most recent diff data. The benefit here is there is no need for extra network traffic to reach consensus about in-time data or a fixed difficulty.  All blocks generated closest to the diff the network can handle will be processed. So priority of a block to be processed would be calculated on a PR as

priority = absolute(quorumDiff - effectiefBlockDiff)

The lowest "priority” being processed first, obviously.

**Comment by qwahzi** [comment] 2023-05-25 02:36
Closing for now, since dynamic PoW was implemented in V19 and then later removed for balance + LRU prioritization: https://docs.nano.org/protocol-design/spam-work-and-prioritization/

**Closed by qwahzi** 2023-05-25 02:36 UTC
Labels: enhancement, question
