### ISSUE TITLE
Deadlock encountered in V16.3

### ISSUE THREAD

**Issue by rkeene** [nanocurrency/nano-node#1418] opened 2018-11-30 15:36 UTC
[thread_apply_all_bt.txt](https://github.com/nanocurrency/raiblocks/files/2633950/thread_apply_all_bt.txt)

**Comment by cryptocode** [comment] 2019-01-17 19:46
Use this ticket to investigate if BOOST_LOG can cause deadlocks when taking boost-logging functions as input  - if so factor out into locals.

**Comment by rkeene** [comment] 2019-01-23 16:07
We can't get enough information from the backtrace nor reproduce this easily.  We're going to do a bit more work on this but may push this off while trying to replicate it.

**Comment by zhyatt** [comment] 2019-02-12 21:51
@cryptocode What OSs has this been tested against and what is remaining to test before closing out?

**Comment by cryptocode** [comment] 2019-02-13 09:34
Closing this as unable to reproduce on macOS and Linux and no recent reports. I've also gone through every instance of BOOST_LOG to see if it can deadlock by streaming in via functions that does logging, but there are no such instances AFAICT.

**Closed by cryptocode** 2019-02-13 09:34 UTC
Labels: bug, medium effort remaining
