### ISSUE TITLE
Imported accounts appear to create invalid blocks

### ISSUE THREAD

**Issue by elliottneilclark** [nanocurrency/nano-node#633] opened 2018-02-16 19:05 UTC
**Description of bug:**
After importing a set of accounts from backup json file any rpc call with those accounts returns a block that never makes it anywhere.

**Steps to reproduce the issue:**
Wiped everything in /root/RaiBlocks except the backup dir.
synched, 
then created a  new wallet
then --wallet_import --file --wallet. 
The accounts show up when I --wallet_list 
The accounts correctly show that they have their correct balance when I curl wallet_balances. 
When I curl account_history it has all the blocks that the block explorer thinks should be there. 

**Describe the results you received:**
When I try and do something that would create a new block it returns a block id. 

However that block id never makes it out to the lattice. If I try and send from one account in my wallet to another, and then receive the block nano responds that it can't receive that block; it doesn't exist.

If I call block with the return value of a send call, immediately after sending, the node returns Block not found.

It looks very much like nano is creating invalid blocks for imported accounts. Meaning that all nano from my imported accounts is un-usable.

**Describe the results you expected:**
Blocks get stored and broadcast.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Environment**:
Linux using latest docker.

**logs**
The logs don't contain any reference of the block that's being created incorrectly.

I do see this log message right after trying to send

[2018-02-16 19:05:06.370022]: Cached work invalid, regenerating

**Comment by PlasmaPower** [comment] 2018-02-16 19:16
Can you use the RPC to get the contents of the apparently invalid block?

Also, are both nodes fully synced?

**Comment by elliottneilclark** [comment] 2018-02-16 23:12
> Can you use the RPC to get the contents of the apparently invalid block?
I ran the following python code:

```python
block = self.client.send(wallet, source, dest, ammount)
print(block)
print(self.client.block(block))       
```

Saw the correct rpc calls in the logs. However the block call came back with Block does not exist.

**Comment by elliottneilclark** [comment] 2018-02-21 00:02
Any movement on this? This bug means that all xrb in my wallet is totally lost despite following the instructions on the wiki. Seems like being able to backup and import a wallet on linux would be important

**Comment by PlasmaPower** [comment] 2018-02-21 00:03
Could you enable ledger processing logging then try to generate a block?

**Comment by PlasmaPower** [comment] 2018-02-21 06:29
I've seen this type of corruption once in the past. If I recall correctly, they recovered the key by logging it in the backup import procedure. I'll see if that could help your problem.

Unfortunately I don't know why this issue exists in the first place.

**Comment by elliottneilclark** [comment] 2018-02-22 01:05
This doesn't seem to be a race or anything like that. I've created, imported, and destroyed wallets lots of different times.

However putting debug logging into wallet_store::import does allow me to then use --wallet_add_adhoc. Not sure what that means for where the bug is.

**Comment by elliottneilclark** [comment] 2019-01-06 21:38
I've stopped using nano so I can't really test anymore.

**Comment by zhyatt** [comment] 2019-01-14 12:35
Thanks for confirming. We are closing this as we are unable to reproduce. Feel free to reopen if issue is still found in current versions.

**Closed by zhyatt** 2019-01-14 12:35 UTC
Labels: bug
