### ISSUE TITLE
V18 High CPU / MEMORY

### ISSUE THREAD

**Issue by udikantz** [nanocurrency/nano-node#1794] opened 2019-02-28 23:02 UTC
I am using a centos 7 dedicated with ssd ( SAMSUNG 970 pro) ,
INTEL CORE I9 processor, 100MB upload/download connection
16GB RAM,

nano_node process uses 70-150% CPU constantly also takes about 60% of the memory available on the machine.

It doesn't seem to be normal, Is there anyway to lower these usage values and keep the node as a a node to send /receive  transactions server.

**Comment by zhyatt** [comment] 2019-02-28 23:16
If you are upgrading to V18 there is a database upgrade happening in the background that results in higher CPU and disk IO usage during the process. Some details are included in the release announcement here: https://medium.com/nanocurrency/the-dolphin-release-has-arrived-6df21c4f06a8#9c18. Once the upgrade is done, resource usage should drop back to previous levels. You can check your log files and if you see “Upgrading sideband information for account X... height Y” the upgrade is still in progress.  The message “Completed sideband upgrade” confirms it has completed.

**Comment by udikantz** [comment] 2019-03-01 06:54
The upgrade is completed successfully a few days ago,
And CPU remain high none stop , I am sure it is not the issue.

```

{
    "version": "2",
    "rpc_enable": "true",
    "rpc": {
        "address": "::1",
        "port": "7076",
        "enable_control": "true",
        "max_json_depth": "20",
        "version": "1"
    },
    "node": {
        "version": "18",
        "peering_port": "7075",
        "bootstrap_fraction_numerator": "1",
        "receive_minimum": "1000000000000000000000000",
        "logging": {
            "version": "7",
            "ledger": "false",
            "ledger_duplicate": "false",
            "vote": "false",
            "network": "false",
            "network_message": "false",
            "network_publish": "false",
            "network_packet": "false",
            "network_keepalive": "false",
            "network_node_id_handshake": "false",
            "node_lifetime_tracing": "false",
            "insufficient_work": "true",
            "log_rpc": "true",
            "bulk_pull": "false",
            "work_generation_time": "true",
            "upnp_details": "false",
            "timing": "false",
            "log_to_cerr": "false",
            "max_size": "134217728",
            "rotation_size": "4194304",
            "flush": "true",
            "log_ipc": "true",
            "min_time_between_output": "5"
        },
        "work_peers": "",
        "preconfigured_peers": [
            "rai.raiblocks.net"
        ],
        "preconfigured_representatives": [
            "xrb_3arg3asgtigae3xckabaaewkx3bzsh7nwz7jkmjos79ihyaxwphhm6qgjps4",
            "xrb_2stofnrxuz3cai7ze75o174bpm7scwj9jn3nxsn8ntzg784jf1gzn1jjdkou",
            "xrb_1q3hqecaw15cjt7thbtxu3pbzr1eihtzzpzxguoc37bj1wc5ffoh7w74gi6p",
            "xrb_3dmtrrws3pocycmbqwawk6xs7446qxa36fcncush4s1pejk16ksbmakis78m",
            "xrb_3hd4ezdgsp15iemx7h81in7xz5tpxi43b6b41zn3qmwiuypankocw3awes5k",
            "xrb_1awsn43we17c1oshdru4azeqjz9wii41dy8npubm4rg11so7dx3jtqgoeahy",
            "xrb_1anrzcuwe64rwxzcco8dkhpyxpi8kd7zsjc1oeimpc3ppca4mrjtwnqposrs",
            "xrb_1hza3f7wiiqa7ig3jczyxj5yo86yegcmqk3criaz838j91sxcckpfhbhhra1"
        ],
online_weight_minimum": "60000000000000000000000000000000000000",
        "online_weight_quorum": "50",
        "password_fanout": "1024",
        "io_threads": "32",
        "network_threads": "64",
        "work_threads": "64",
        "enable_voting": "false",
        "bootstrap_connections": "8",
        "bootstrap_connections_max": "64",
        "callback_address": "",
        "callback_port": "0",
        "callback_target": "",
        "lmdb_max_dbs": "512",
        "block_processor_batch_max_time": "5000",
        "allow_local_peers": "false"
    },
    "opencl_enable": "false",
    "opencl": {
        "platform": "0",
        "device": "0",
        "threads": "1048576"
    }
}

It was like that also on previous versions on the nano_node

```

**Comment by wezrule** [comment] 2019-03-01 07:24
I see you are running master and some upgrades didn't go through in the config (rai.raiblocks.net in preconfigured peers should now point to the nano domain for instance), so it's possible others havent gone through either. This can happen when we add an additional feature to a "version" being upgraded to at a different time during the release cycle but someone has already upgraded the version number from an earlier feature. This is why we recommend only using release branches. This might not be a problem just something I noticed.

A few things might be helpful to diagnose the issue, run this on a terminal for the nano_node process. It will display the threads and which ones are doing the most work.
`top -H -p <node_pid>`

Run this RPC call `{"action":"stats", "type":"objects" }`. It will print out various things we have in memory.

Check the log file to see if this has any clues.

**Comment by udikantz** [comment] 2019-03-01 11:32
>  I see you are running master and some upgrades didn't go through in the config (rai.raiblocks.net in preconfigured peers should now point to the nano domain for instance), so it's possible others havent gone through either. This can happen when we add an additional feature to a "version" being upgraded to at a different time during the release cycle but someone has already upgraded the version number from an earlier feature. This is why we recommend only using release branches. This might not be a problem just something I noticed.

Actually I had this old json config file from version 16, and just changed the version number,
I am using the new 18 release version which points to old data folder with this config file.

Here are the most consuming thread list
I see the voting is consuming most of the cpu power over time, is there anyway to make the node static so it wont participate in the voting process?

```
PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                   10883 nanode    20   0  138.0g   9.3g   9.2g S 13.3 60.6  16:34.36 Pkt processing                                                                                                            
10963 nanode    20   0  138.0g   9.3g   9.2g S 13.3 60.6 319:23.61 Vote processing                                                                                                           
10900 nanode    20   0  138.0g   9.3g   9.2g S  6.7 60.6  16:31.19 Pkt processing
10902 nanode    20   0  138.0g   9.3g   9.2g S  6.7 60.6  16:34.51 Pkt processing                                                                                                            10911 nanode    20   0  138.0g   9.3g   9.2g S  6.7 60.6  16:31.36 Pkt processing                                                                                                            10926 nanode    20   0  138.0g   9.3g   9.2g S  6.7 60.6  16:34.82 Pkt processing                                                                                                            10928 nanode    20   0  138.0g   9.3g   9.2g S  6.7 60.6  16:35.08 Pkt processing                                                                                                            10932 nanode    20   0  138.0g   9.3g   9.2g S  6.7 60.6  16:31.38 Pkt processing                                                                                                            10936 nanode    20   0  138.0g   9.3g   9.2g S  6.7 60.6  16:32.48 Pkt processing                                                                                                            10940 nanode    20   0  138.0g   9.3g   9.2g S  6.7 60.6  16:30.21 Pkt processing                                                                                                            10944 nanode    20   0  138.0g   9.3g   9.2g S  6.7 60.6  16:32.42 Pkt processing  
```  
 

> Run this RPC call `{"action":"stats", "type":"objects" }`. It will print out various things we have in memory:

[Pasted resaults to paste bin <----](https://pastebin.com/w9weGn00)

**Comment by wezrule** [comment] 2019-03-01 20:23
Well you have `min_time_between_output` in the config file which has not been released yet, so I'm not so sure. Changing the version number is also not recommended as we check for it to see what upgrades need to be done in the config.

Thanks for the details. How many threads does you CPU have?, I wonder if you are using too many:
```
"io_threads": "32",
"network_threads": "64",
"work_threads": "64",
```

This could result in a lot of context switching with interleaving threads.

Your node configuration means that you do not participate in the voting process, however you still need to check the result from votes in elections caused by forks.

**Comment by udikantz** [comment] 2019-03-01 20:36
If I am not wrong the cpu I am using has 32 Threads It should be easy for it to handle here is the cpu spec:
```


Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 158
Model name:            Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Stepping:              12
CPU MHz:               799.804
CPU max MHz:           5000.0000
CPU min MHz:           800.0000
BogoMIPS:              7200.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              16384K
NUMA node0 CPU(s):     0-15
```

**Comment by SergiySW** [comment] 2019-03-01 21:33
Your CPU has 8 cores & 16 threads. 100% CPU usage in Linux means it's fully utilizing 1 thread (of 16). 150% ~ 1.5 threads

**Comment by zhyatt** [comment] 2019-03-01 21:39
@udikantz At this point I would recommend bringing up a fresh V18 node (not from master, but either building yourself from git tag V18.0 or using a provided binary) and adding in your seed/moving over wallets as needed. It sounds like you have potentially been running an unsupported version and the config file may not have been properly migrated as a result. If you are able to get that up and still have issues we can help troubleshoot on that official release version.

**Comment by zhyatt** [comment] 2019-03-12 00:37
@udikantz Were you able to get this sorted out? If so, feel free to close this ticket.

**Comment by udikantz** [comment] 2019-03-12 08:21
Hey,
I have re built the latest release and synched the entire block-latis from scratch and and cpu and memory was still high.

And then I figured out that I am building the node in debug mode following the wiki guide:  
[build nano node](https://github.com/nanocurrency/nano-node/wiki/Build-nano_node-samples) 
and not release mode.

So I rebuilt the node, added the following option: -DCMAKE_BUILD_TYPE=Release
Now the node looks a lot better in terms of cpu, Memory was looking really good at start, using only 1% memory and after few days memory is back to 70% capacity, perhaps there is a memory leak, or is there a good reason that the node will use over 30GB RAM?

**Comment by guilhermelawless** [comment] 2019-03-12 10:53
It's compiled for Release by default if no build type is given.

Memory for the node is usually cached (linux does disk caching in the RAM). It is memory that can be immediately used by other processes. Try command `free -m -h -t` to see the total memory used in the system, and note the buff/cache column.

**Comment by zhyatt** [comment] 2019-11-21 23:08
@udikantz Have you seen high CPU/memory with more recent builds (V19/V20)?

**Comment by zhyatt** [comment] 2021-09-16 23:19
Closing due to no response

**Closed by zhyatt** 2021-09-16 23:19 UTC
