### ISSUE TITLE
Feature request - logs to stdout

### ISSUE THREAD

**Issue by ksemaev** [nanocurrency/nano-node#2171] opened 2019-07-24 08:15 UTC
Although we have this hack in place: https://github.com/nanocurrency/nano-node/blob/master/docker/node/entry.sh#L41-L42  it is not very helpful, as all I can get from it is
> Network: live, version: 19.0
> Path: /home/nano/Nano

While real logs go to ~/logs/log_2019-07-24_08-04-54.537.log etc, and filling the filesystem.

For docker usage we really want all logs on stdout. Can you please add some option for sending them there, instead of `logs` folder and this rotating nano-docker-output.log file?

**Comment by argakiig** [comment] 2019-07-24 14:51
effectually duplicate of #1612 
see #2160 using -l flag

**Closed by argakiig** 2019-07-24 14:51 UTC
