### ISSUE TITLE
Wallet_create on the command line doesn't work with a running daemon

### ISSUE THREAD

**Issue by clemahieu** [nanocurrency/nano-node#458] opened 2018-01-09 08:25 UTC
The database entry is created but the items map in memory isn't updated when the file changes.

The items map in memory could be removed and just always check the database for wallet IDs.

**Comment by brightmonkey** [comment] 2018-01-31 04:09
I was going to take a stab at fixing this, but as far as i can tell wallet_create seems to work. What are the steps I need to do to reproduce the symptoms you see?

**Comment by clemahieu** [comment] 2018-01-31 06:10
I think the issue is if the node is running "rai_node --daemon" and someone runs "rai_node --wallet_create" on the command line, they expect that to be effective in the running node but it's not because the map in rai::wallets isn't updated with the new wallet id.

**Comment by brightmonkey** [comment] 2018-02-01 02:19
Isn't that the equivalent of running two instances of the node? If so, how would node B influence/change the properties of node A running the daemon? Furthermore, if someone wants to add a wallet to node A, why wouldn't they use the RPC command?

**Comment by brightmonkey** [comment] 2018-02-01 02:39
Never mind, I think I answered my own question. Looks like the expectation **is** that node B updates the database and node A is unaware of the change. I'll look into removing the items map and checking the database for wallet IDs instead.

**Comment by brightmonkey** [comment] 2018-02-04 02:06
@clemahieu the majority of command line options don't respect the --data_path flag. Was this a specific design choice? If not I'd like to create and submit a change that allows commands like ./rai_node --wallet_list to use the path defined by --data_path if that's ok with you. The rationale for this is to keep my debug environment entirely separate from the default installation path used by my personal desktop wallet.

**Comment by cryptocode** [comment] 2018-02-04 02:09
@brightmonkey there's a PR fixing that: https://github.com/clemahieu/raiblocks/pull/342

**Comment by PlasmaPower** [comment] 2018-02-04 02:10
There was a PR to fix that, but it got abandoned.

**Comment by brightmonkey** [comment] 2018-02-04 02:13
@cryptocode thanks! 
@PlasmaPower, are you talking about #342 or a different PR?

**Comment by PlasmaPower** [comment] 2018-02-04 02:19
Same PR.

**Comment by brightmonkey** [comment] 2018-02-04 02:23
Looks like it's still open, although it needs a rebase. @SergiySW, is #342 still active?

**Comment by SergiySW** [comment] 2018-02-04 02:43
Updated for recent version https://github.com/clemahieu/raiblocks/pull/586

**Comment by brightmonkey** [comment] 2018-02-07 03:53
@clemahieu there are ~180 places in the code that reference the wallets.items map. Were you thinking of replacing all of them with direct db reads? I don't know what impact removing the map entirely would have on performance, but I would think accessing a map in memory would always be faster than file IO access to a database on disk. 

As an alternative, would it be reasonable to add an RPC command called "wallet_refresh" that updates the wallets.items map from the database? A user could call "rai_node --wallet_create" to create the new wallet, then make an RPC call to "wallet_refresh" to have the running node pick up the new wallet and refresh the map. Thoughts?

**Comment by cclafferty** [comment] 2018-03-22 16:01
I've found this exact issue when attempting to run a representative node. I must admit it took me a long time to find the problem. Most installation guides instruct to run ./rai_node --wallet_create which is creating a wallet the daemon knows nothing about. I would hazard a guess that most representative nodes are not voting because of this, as it's easier to miss. See nanode.co for quite a large list of offline representatives.

If this bug looks too involved to fix right now perhaps directing people to use the RPC methods for creating wallets would be best? Alternatively inform them they must restart the daemon when using the command line?

**Comment by rkeene** [comment] 2018-08-23 17:30
We can also have methods that change the database in ways the daemon would need to be notified of fail if the daemon is running.

**Comment by argakiig** [comment] 2018-09-22 06:37
So, to understand are we wanting to block CLI calls that would modify the database if an instance of the daemon or wallet is running?

**Comment by SergiySW** [comment] 2019-01-26 16:19
Running daemon will update wallets list each 5 minutes in version 18.0 https://github.com/nanocurrency/nano-node/pull/1619

**Comment by zhyatt** [comment] 2019-01-30 17:20
Resolved in #1619

**Closed by zhyatt** 2019-01-30 17:20 UTC
Labels: bug
