### ISSUE TITLE
'delegators' and 'delegators_count' RPC commands run very slowly or not at all

### ISSUE THREAD

**Issue by kilkelly** [nanocurrency/nano-node#1517] opened 2018-12-30 18:00 UTC
**Issue**:
When running the `delegators` or `delegators_count` RPC commands on a node the response is either very slow or can even lock up / crash the node.

**Steps to reproduce the issue**:
Run either the `delegators` or `delegators_count` via RPC on the node and wait for the results.

**Describe the results you received**:
My node never returned results and became unresponsive to further RPC commands i.e. locked up.

**Describe the results you expected**:
Expected to see results as [documented](https://github.com/nanocurrency/raiblocks/wiki/RPC-protocol#delegators) in the Nano wiki.

**Environment**:
- OS information: Linux li293-21 4.18.16-x86_64-linode118 # 1 SMP PREEMPT Mon Oct 29 15:38:25 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Nano Node version: V17.0
- Docker: 18.06.1-ce
- System stats: 2 GB RAM, 1 CPU Core, Linode VPS

**Possible Solution**:
Optimize how the `delegators` and `delegators_count` RPC commands interact with the ledger.

**Comment by cryptocode** [comment] 2018-12-31 00:13
There's no inverse lookup table for delegators, so this currently entails looping through the account tables (v0 and v1) and, for each account, reading the rep block to figure out if the block's representative matches the account being queried. Faster lookups are possible, but it seems like it will be at cost of denormalization (a larger ledger)

**Comment by kilkelly** [comment] 2018-12-31 13:02
That was my hunch as well. It wouldn't be worth any ledger size increase just for this command. Looks like some stronger hardware is required on my side. Thanks @cryptocode 👍

**Comment by zhyatt** [comment] 2018-12-31 23:37
Closing out due to optimization tradeoffs not worth it.

**Comment by meltingice** [comment] 2019-01-09 16:41
For what it's worth, I'd take a larger ledger in order to speed up this call. It's a feature I like having in NanoCrawler, and the RPC call is painfully slow.

**Comment by zhyatt** [comment] 2019-01-09 17:17
Reopening for further discussion of tradeoffs

**Comment by meltingice** [comment] 2019-01-09 17:36
This is perhaps something that would greatly benefit from a customizable database adapter. Could leave the current lmdb implementation as default with the slow delegators call, but allow other database systems (or maybe even a reconfigured lmdb) if desired.

**Comment by kilkelly** [comment] 2019-01-09 21:22
Alternatively I wonder if it is possible to have a config.json setting for enabling the denormalisation required to achieve the faster `delegators` call? A node operator probably wouldn't mind a larger ledger if they were working with that call and `delegators_count` a lot.

**Comment by zhyatt** [comment] 2019-01-09 21:48
@kilkelly Indeed. Making this optional was an approach I was going to discuss with the team.  Will get an update on this within the next week or so.

**Comment by guilhermelawless** [comment] 2019-01-12 17:21
Proposing an alternative:

Allow `delegators` to receive a list of accounts instead of just one, returning a lookup table account->delegators.

Would still be O(n) on accounts, so it would provide benefits for crawlers who can call this every minute or so to update.

**Comment by zhyatt** [comment] 2019-01-28 19:46
It is taking a bit longer than anticipated to dig into this but will be considering for future release.

**Comment by kilkelly** [comment] 2019-01-28 20:22
Is the upcoming "sideband" functionality something that can be utilized for optional, configurable collection of delegator counts or is it just for block info?

BTW I did manage to collect delegator counts for representative addresses I am tracking without using the `delegators_count` RPC command but it required navigating through the entire ledger with the `ledger` RPC command.

**Comment by cryptocode** [comment] 2019-01-28 20:23
@kilkelly what's the performance of that solution?

**Comment by kilkelly** [comment] 2019-01-28 23:42
It varies between 30 minutes to almost 3 hours sometimes. Feels kind of random but that's probably because of regular transaction activity the node is processing also. On a more powerful node it shouldn't take too long.

**Comment by cryptocode** [comment] 2019-02-19 21:39
@kilkelly I'm not able to reproduce it taking that long (on master) - 10 seconds at most. Do you have an exact RPC call example?

**Comment by kilkelly** [comment] 2019-02-19 23:11
Hi @cryptocode , it was a normal, vanilla `delegators` RPC call as outlined in the RPC wiki. I believe the time taken for the call to complete is directly related to the strength of the hardware. I'm currently upgrading my node hardware (8 core, 30 GB) and it takes around 10 - 15 seconds on there. My old, weak node (2 core, 2 GB) was the one giving the extremely slow call.

**Closed** 2019-09-06 20:00 UTC
Labels: quality improvements
