### ISSUE TITLE
Remove gap_previous check from epoch_block_impl

### ISSUE THREAD

**Issue by rkeene** [nanocurrency/nano-node#1392] opened 2018-11-19 17:48 UTC
As a follow-up to #1255

**Comment by SergiySW** [comment] 2019-01-23 20:13
Fixed with PR https://github.com/nanocurrency/nano-node/pull/1559
Can be removed from v18 as duplicate of PR

**Comment by SergiySW** [comment] 2019-01-23 20:52
Closed with https://github.com/nanocurrency/nano-node/pull/1559

**Closed by SergiySW** 2019-01-23 20:52 UTC
Labels: functionality quality improvements
