### ISSUE TITLE
RPC: pending response contains no list, if nothing is pending

### ISSUE THREAD

**Issue by codesoap** [nanocurrency/nano-node#3161] opened 2021-03-21 22:10 UTC
**Description of bug:**

According to https://docs.nano.org/commands/rpc-protocol/#pending, the response to the `pending` RPC should contain a field named `blocks` which contains a list of pending blocks. When no blocks are pending, I expect an empty list, but I'm getting an empty string instead. The JSON parser I'm using (Go standard library) does not accept an empty string when it expects a list of strings.

I have tested against https://mynano.ninja/api/node, which returns this version info:

```json
{
  "rpc_version": "1",
  "store_version": "21",
  "protocol_version": "18",
  "node_vendor": "Nano V22.0",
  "store_vendor": "RocksDB 6.13.3",
  "network": "live",
  "network_identifier": "991CF190094C00F0B68E2E5F75F6BEE95A2E0BD93CEAA4A6734DB9F19B728948",
  "build_info": "91535b7b \"GNU C++ version \" \"7.5.0\" \"BOOST 107000\" BUILT \"Mar 20 2021\""
}
```

**Steps to reproduce the issue:**
```bash
curl -s -H 'Content-Type: application/json' -d '{"action": "pending", "account": "nano_3i1aq1cchnmbn9x5rsbap8b15akfh7wj7pwskuzi7ahz8oq6cobd99d4r3b7"}' https://mynano.ninja/api/node
```

**Describe the results you received:**
The `blocks` field in the response is an empty string (`{"blocks":""}`).

**Describe the results you expected:**
I would have expected the `blocks` field to be an empty list (`{"blocks":[]}`).

**Comment by cryptocode** [comment] 2021-03-22 09:36
@codesoap This is due to the json reader/writer used, see also #2188 and #1871 

For now, it should be possible to implement workarounds in Go, see for instance how the issue is handled in https://github.com/hectorchu/gonano/blob/master/rpc/account.go

**Comment by codesoap** [comment] 2021-03-22 15:37
Thanks for the info! I must say, I'm a bit surprised that such a fundamental bug has never been fixed. I'll make due with a [custom unmarshaler](https://golang.org/pkg/encoding/json/#Unmarshaler), which interprets the empty string as an empty list.

**Comment by cryptocode** [comment] 2021-03-22 16:26
Closing as this is covered by other issues and submitter has a workaround.

**Closed as completed by cryptocode** 2021-03-22 16:26 UTC
