### ISSUE TITLE
Wallet RPC endpoints are much slower than block_create + process

### ISSUE THREAD

**Issue by PlasmaPower** [nanocurrency/nano-node#537] opened 2018-01-25 02:04 UTC
See #536, a PR to add a load tester written in Rust.

On my system, when run with `--precompute-blocks` (create blocks with `block_create` then `process` them), the test takes 45 seconds.

When run without `--precompute-blocks` (use the `send` and `receive` endpoints), the test takes 2 minutes.

**Comment by SergiySW** [comment] 2019-01-09 16:37
No difference with -n 1 & Release build here.
-n 2 & higher sometimes failing to catch up or genesis account info

**Comment by SergiySW** [comment] 2019-01-09 16:55
@PlasmaPower could you remember build type with your results?

**Comment by SergiySW** [comment] 2019-01-09 18:57
Thanks, @PlasmaPower !

**Comment by zhyatt** [comment] 2019-01-14 12:41
Closing as we couldn't reproduce original results that were an issue and looks to have been fixed in prior release.

**Closed by zhyatt** 2019-01-14 12:41 UTC
Labels: bug, rai_node
