### ISSUE TITLE
Improve vote uniquer cleanup

### ISSUE THREAD

**Issue by rkeene** [nanocurrency/nano-node#1551] opened 2019-01-03 17:08 UTC
It's been observed that the vote uniquer cleanup (fixed in #1473) was not sufficient and a more complicated mechanism (like #1472) may be needed, as well as forcing the container to shrink periodically.

**Comment by cryptocode** [comment] 2019-01-17 19:30
@wezrule since you're going to look into this, I did an experiment a while back with deterministic cleanup (hash-consing factory instead of a uniquer) https://github.com/nanocurrency/nano-node/pull/1561

I think a better uniquer cleanup algo is going to be a lot less code than 1561, but figured I should mention it. I'm not sure if it's the way to go, I didn't see much of a difference when testing as I couldn't get the uniquer to grow much (maybe I didn't run long enough).

**Comment by wezrule** [comment] 2019-01-29 15:19
It would be good to check using the RPC call in #1632 if anyone has memory issues and check the size of the votes then to see if this is still an issue.

**Comment by zhyatt** [comment] 2019-02-07 15:35
Closing this out as not currently reproducible. Will be doing some additional monitoring with RPC memory call in the future to try getting more details about this should it occur again.

**Closed by zhyatt** 2019-02-07 15:35 UTC
Labels: functionality quality improvements
