### ISSUE TITLE
V18 - RPC Pending request returns empty list for a period of time after callback

### ISSUE THREAD

**Issue by bbedward** [nanocurrency/nano-node#1793] opened 2019-02-26 19:13 UTC
Not sure if related to #1488 

Basically on V17 and now V18, when an account has a pending block - the RPC `pending` request returns an empty list for a period of time, usually around 30-60s.

It's particularly peculiar because since V18, the callback fires almost instantly for the block, but then an RPC `pending` request returns no blocks for almost a minute afterwards for the same link as the block that was sent to the callback.

Also `account_balance` for the link account shows a pending balance, just the pending request is returning no blocks.

Expected behavior: To be able to retrieve pending blocks via rpc pending almost instantly after the callback.

Will provide any other information thats needed.

**Comment by bbedward** [comment] 2019-02-26 19:42
Specifying `include_active:true` in the rpc pending request removes the delay, but I suspect still might be a bug since callback is supposed to happen after confirmation - at least that's from my understanding.

**Comment by severalif** [comment] 2019-02-27 07:23
I have also experienced this on my node (https://repnode.org). Basically, that a block has been confirmed (via RPC callback), the pending amount is shown in account_balance, but it takes some time (not sure exactly how long time) before the block is available in the pending RPC command.

**Comment by icarusglider** [comment] 2019-04-04 17:24
Confirmed. Tested with local node and two wallets. Wallet 1 has no password, Wallet 2 has password. Python script listening for callbacks and polling pending for each wallet account every 100ms.

Wallet 1:
```
1554398343.6380167 callback received: D3370C871430061BB87BD928E412EDB99C09C8C03411C7689FEB715B8E436376 to xrb_1zdt7i8u3r48eu8hgogyjw18muigsuhzreyhzxurfu9g9sh5r8q5kbj1cxt7 from xrb_1ji89scnwyyeqab1fyzn7ymyfmmkkw4m7n5p1bqg6xsqaepgkwpjmd73cstz
1554398344.1798704 callback received: AF354B88181E067C3F3B0EFCFA5E305DE8C17A358AEF4CD27D7BC7C852010334 for xrb_1zdt7i8u3r48eu8hgogyjw18muigsuhzreyhzxurfu9g9sh5r8q5kbj1cxt7
```
Transaction is seen in callback and _immediately_ received, issuing another callback for the local account block. Nothing shows in pending requests during this time.

Wallet 2:
```
1554398348.6657329 callback received: 06F2ADA7C287C7936199A58382583C3BD8B9C2F972114E9C9B41B072CA8B0C6B to xrb_1zcqn6rwzaqde4fc1u5ou4uqi38txizuof6mrxox1kdr5doxbmwft57jfo16 from xrb_1ji89scnwyyeqab1fyzn7ymyfmmkkw4m7n5p1bqg6xsqaepgkwpjmd73cstz
1554398368.7133865 pending block: xrb_1zcqn6rwzaqde4fc1u5ou4uqi38txizuof6mrxox1kdr5doxbmwft57jfo16 - 06F2ADA7C287C7936199A58382583C3BD8B9C2F972114E9C9B41B072CA8B0C6B
```
Callback shows pending block right away. RPC `pending` does not show this block until approximately 20 seconds later. When wallet is then unlocked with password the transaction is received (issuing another callback) and successive transactions show only in callbacks.

**Comment by icarusglider** [comment] 2019-04-04 18:36
Added `accounts_pending` to the set of checks and added confirmation time review as well.

```
1554402825.6451795 callback received: D6E0BFC06A237C948A1E93CDD77F01ABE183AE798962CA0AF336628F07D22493 to xrb_1zcqn6rwzaqde4fc1u5ou4uqi38txizuof6mrxox1kdr5doxbmwft57jfo16 from xrb_1ji89scnwyyeqab1fyzn7ymyfmmkkw4m7n5p1bqg6xsqaepgkwpjmd73cstz
1554402842.0908332 [`pending`] pending block: xrb_1zcqn6rwzaqde4fc1u5ou4uqi38txizuof6mrxox1kdr5doxbmwft57jfo16 - D6E0BFC06A237C948A1E93CDD77F01ABE183AE798962CA0AF336628F07D22493
1554402842.09097 [`accounts_pending`] pending block: xrb_1zcqn6rwzaqde4fc1u5ou4uqi38txizuof6mrxox1kdr5doxbmwft57jfo16 - D6E0BFC06A237C948A1E93CDD77F01ABE183AE798962CA0AF336628F07D22493
1554402842.17681 block D6E0BFC06A237C948A1E93CDD77F01ABE183AE798962CA0AF336628F07D22493 was confirmed at 1554402825.622
```
This confirms the callback is being sent on confirmation (both at 1554402825) and not showing in either `pending` or `accounts_pending` until 1554402842 (17 seconds later).

**Comment by cryptocode** [comment] 2019-04-05 08:32
I believe this is due to hashes lingering in active roots until the next confirmation request happens (the old announcement loop). v19 should remove the delay as the is-active check is replaced with code based on confirmation height.

**Comment by icarusglider** [comment] 2019-07-01 15:42
This appears to have been resolved in V19RC5:

```
1561995502.96448 callback received: 3CC0DF60445E0E47A363EC94CC1AED3B89B1A4BB97DE44375D8B9A1C73EB3592 to nano_3fn9k6moiecxkoh3x8nak8btid4pkxqu4asj3hcazujjdfnsg19h8g3m4fud from nano_1carus1d8oar7cmaf6n7eayim9rb5jbwosgfwzy4cbchkgz6b5hi1yec71un
1561995502.9773712 [`pending`] pending block: nano_3fn9k6moiecxkoh3x8nak8btid4pkxqu4asj3hcazujjdfnsg19h8g3m4fud - 3CC0DF60445E0E47A363EC94CC1AED3B89B1A4BB97DE44375D8B9A1C73EB3592
1561995502.9776764 [`accounts_pending`] pending block: nano_3fn9k6moiecxkoh3x8nak8btid4pkxqu4asj3hcazujjdfnsg19h8g3m4fud - 3CC0DF60445E0E47A363EC94CC1AED3B89B1A4BB97DE44375D8B9A1C73EB3592
1561995503.1178856 block 3CC0DF60445E0E47A363EC94CC1AED3B89B1A4BB97DE44375D8B9A1C73EB3592 was confirmed at 1561995502.95
```

```
1561995539.2832167 callback received: 382C759F967ED45C162AD456A8F559D9930CE448033EFC00EEC167C8ABD052B2 to nano_3nr1irrjog74byk4e5e8jsafh3zzfeqe8ka4r77x9fzqwqhdibsmdbi4k5o9 from nano_1carus1d8oar7cmaf6n7eayim9rb5jbwosgfwzy4cbchkgz6b5hi1yec71un
1561995539.3640697 [`pending`] pending block: nano_3nr1irrjog74byk4e5e8jsafh3zzfeqe8ka4r77x9fzqwqhdibsmdbi4k5o9 - 382C759F967ED45C162AD456A8F559D9930CE448033EFC00EEC167C8ABD052B2
1561995539.364272 [`accounts_pending`] pending block: nano_3nr1irrjog74byk4e5e8jsafh3zzfeqe8ka4r77x9fzqwqhdibsmdbi4k5o9 - 382C759F967ED45C162AD456A8F559D9930CE448033EFC00EEC167C8ABD052B2
1561995539.4266112 block 382C759F967ED45C162AD456A8F559D9930CE448033EFC00EEC167C8ABD052B2 was confirmed at 1561995539.276
```

**Closed** 2019-07-01 15:43 UTC
